### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by radarhere**

### CODE REVIEW

**Comment by samsonasik** [comment]
not sure, but changelog entry _probably_ generated via pull requests in milestone

**Comment by radarhere** [comment]
You're saying that if this PR was merged, it would simply be automatically overwritten in the future? If so, fair enough, and feel free to close this. Thanks.

**Comment by samsonasik** [comment]
ping @weierophinney as should now about changelog generation :)

**Comment by weierophinney** [comment]
@samsonasik We don't overwrite old entries; we only generate *new* entries.

**Pull request merged**
