### PR TITLE
Incorrect response for HTTP status code 414

### PR DESCRIPTION
**Pull request by mathiasverraes**
see http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

### CODE REVIEW

**Comment by mathiasverraes** [comment]
Just curious, is there a reason for not merging this straight away into a development or a 2.3.5 branch?

**Comment by Ocramius** [comment]
Mainly because I'd need to checkout locally and merge in both branches
manually: kinda hard from a phone ;-)

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by mathiasverraes** [comment]
Makes sense :-)

**Comment by Ocramius** [comment]
Merged, thanks @mathiasverraes!

`master`: zendframework/zf2@9d86b442bddd728612280bddcfe116d368367cea
`develop`: zendframework/zf2@cf921eef1a1c4fa5bd6bfa8637163d60396207dc

**Pull request merged**
