### PR TITLE
Estonian IDN definition & fixed binary code for HOST_DNS_OR_IPV4_OR_IPV6_OR_REGNAME

### PR DESCRIPTION
**Pull request by netcreatoreu**
Before this changed we cannot properly check URL like:
- http://plekitööd.ee/
  using \Zend\Uri\Http

### CODE REVIEW

**Comment by Ocramius** [comment]
@netcreatoreu can you add relevant example data to test fixtures?

**Comment by netcreatoreu** [comment]
@Ocramius can be as a comment?
```
$url = 'http://plekitööd.ee/';
$uri = new Zend\Uri\Http($url);
var_dump($uri->isValid());
```
This code responsed FALSE in ZF 2.3.4, but should be TRUE.

**Comment by Ocramius** [comment]
@netcreatoreu yes, what I'm asking is for a domain such as that to be introduced in the existing test suite. Look at the existing tests and create an example `.ee` in there ;-)

**Comment by netcreatoreu** [comment]
@Ocramius ok, test added. Also updated a set of characters for Estonian IDN (source : https://www.iana.org/domains/idn-tables/tables/pl_et-pl_1.0.html  )

**Comment by netcreatoreu** [comment]
@Ocramius This is not "our" failed ;-)
```
There was 1 failure:

1) ZendTest\Cache\Storage\Adapter\MemoryTest::testClearExpired

Failed asserting that false is true.

/home/travis/build/zendframework/zf2/tests/ZendTest/Cache/Storage/Adapter/CommonAdapterTest.php:1048

FAILURES!

Tests: 1479, Assertions: 2200, Failures: 1, Skipped: 1099.
```

**Comment by Ocramius** [comment]
Restarted the failed worker

**Comment by Ocramius** [comment]
Merged, thanks @netcreatoreu!

`master`: zendframework/zf2@1225ce013c34df91dcb9df8e1517343ef977bf9a
`develop`: zendframework/zf2@7cd95240fe7a143ae99500f279fd27bd5925e2b4

**Pull request closed without merging**
