### PR TITLE
Switch to PSR-4

### PR DESCRIPTION
**Pull request by afurculita**
This PR changes all the composer.json from all the library components to handle the autoload using PSR4

### CODE REVIEW

**Comment by Martin-P** [comment]
PSR-4 was proposed in PR #6357.

**Comment by afurculita** [comment]
This PR refers to all the components, not the full stack. Also as Jordi Boggiano specifies in her article http://seld.be/notes/psr-4-autoloading-support-in-composer, the "target-dir" is deprecated, it was just a hack and it recommends PSR-4

**Comment by Ocramius** [comment]
This requires a change of how the submodules are split: may be a bit more complicated than "just doing it"

**Comment by gianarb** [comment]
In my opinion this "transversal" commit between components create a lot of history problem :)
PSR-0 is deprecated and this is an important improvement but maybe we could apply it after split..

**Comment by Ocramius** [comment]
@gianarb this is just the `composer.json`: no directory structure changes, as far as I can see

**Comment by weierophinney** [comment]
I tested this just now by cloning the `Component_ZendVersion` repo, making the changes as noted in this PR, and installing; worked perfectly.

**Comment by weierophinney** [comment]
I'm also making this change to the project `composer.json`:

```json
"psr-4": {
    "Zend\\": "library/Zend/"
}
```

I'm leaving the tests as PSR-0, as we have some test assets with underscores in class names, which PSR-4 does not support; we'll update those when we split the components out into their own repos.

Thanks for the patch, @afurculita !

**Pull request merged**
