### PR TITLE
Email validator hostname check for not empty

### PR DESCRIPTION
**Pull request by freax**
Sometimes there is a warning because of empty `hostname` parameter in `checkdnsrr` function.

### CODE REVIEW

**Comment by Ocramius** [comment]
@freax please rebase and provide a test case for the hostname affected by this bug.

**Comment by DASPRiD** [comment]
@Ocramius adding a hostname to the test suit which could fail any time? Sounds like a bad idea.

**Comment by Ocramius** [comment]
I mean that data-providers need to be adjusted ;-)

**Comment by freax** [comment]
I don't think this PR needs a test case, because it's nothing to break actually.
This condition fails if `hostname` will be empty anyway, but this PR provides no more thipple warning in this case.
I got this warnings twise and I can't reproduce it.
Actually, I think it's a pretty rare case when script can't get MX-record for hostname.

**Comment by Ocramius** [comment]
> I don't think this PR needs a test case, because it's nothing to break actually.

code changes affecting branching of execution paths **always require** testing, regardless of the impact they have.

 > This condition `fails` if hostname will be empty anyway, but this PR provides no more thipple warning in this case.

And your test should actually try to reproduce the warning instead: reaching the point where you can reproduce the warning will also give you a better understanding the problem.

 > Actually, I think it's a pretty rare case when script can't get MX-record for hostname.

You can inject a fake hostname validator to get to that.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-validator/issues/99

**Pull request closed without merging**
