### PR TITLE
Annotations in EventManager and EventManagerInterface updated to include instances of EventInterface as $target

### PR DESCRIPTION
**Pull request by AGmakonts**

### CODE REVIEW

**Comment by samsonasik** [comment]
need rebase

**Comment by weierophinney** [comment]
If you could rebase this, I'd appreciate it.

**Comment by AGmakonts** [comment]
@weierophinney should be ok now.

**Comment by weierophinney** [comment]
@AGmakonts This still needs to be rebased; it's unmergeable currently due to conflicts.

**Comment by weierophinney** [comment]
24-hour warning; I need a rebase by tomorrow, 19 March 2015, if you want this included in 2.4; otherwise, I'll remove the milestone, and we can review at a later date.

**Comment by AGmakonts** [comment]
@weierophinney sorry for delay, I'll commit changes later today.

**Comment by AGmakonts** [comment]
I saw that those changes are already in develop, closing this one

**Pull request closed without merging**
