### PR TITLE
Fix: Email Validator vs IDN

### PR DESCRIPTION
**Pull request by svyatoslav-kubakh**
Non-latin emails validation

### CODE REVIEW

**Comment by moderndeveloperllc** [comment]
I don't think you can use `idn_to_ascii()` in this class as Zend\Validator does not require the `intl` extension to be present. If you want to validate non-Latin emails, it might be better to write an Zend\I18n validator that uses that function. Thoughts @DASPRiD?

**Comment by weierophinney** [comment]
Two potential options:

- Have it use `idn_to_ascii`, but only if ext/intl is installed. This could be achieved via a method call:
```php
$this->getLocalizedLocalPart();

private function getLocalizedLocalPart()
{
    if (extension_loaded('intl')) {
        return idn_to_ascii($this->localPart);
    }
    return $this->localPart;
}
```
- **or** move it into the `Zend\I18n\Validator` namespace.

Your pick. If you can do this by 9 March 2015, I can include it in 2.4.

**Comment by moderndeveloperllc** [comment]
@svyatoslav-kubakh I can do the change and move if you don't want to deal with it.

**Comment by svyatoslav-kubakh** [comment]
Hello, everyone. I apologize for my absence. Thank you for your help and advice. I will make a second attempt to fix within 1-2 days. If the patch is rejected again, you give in turn. :-)

**Comment by moderndeveloperllc** [comment]
@svyatoslav-kubakh We're your fixes made on another PR, or have you decided not to fix this?

**Comment by svyatoslav-kubakh** [comment]
That's correct. https://github.com/zendframework/zf2/pull/7281

**Pull request closed without merging**
