### PR TITLE
Update PostCode.php

### PR DESCRIPTION
**Pull request by SamHecquet**
Exclude french zip codes with invalid departments : 00, 96 et 99.
Exclude invalid Norway zip code  : 0000.

### CODE REVIEW

**Comment by Ocramius** [comment]
@SamHecquet this requires additional tests with example codes from those areas

**Comment by bakura10** [comment]
98 is not a valid French postcode neither, as far as I know :o.

**Comment by weierophinney** [comment]
I'd like to schedule for 2.4.0... but could really use some unit tests, @SamHecquet ...

**Comment by weierophinney** [comment]
24-hour warning; I need tests by tomrrow, 19 March 2015, if you want this included in 2.4; otherwise, I'll remove the milestone, and we can review at a later date.

**Comment by SamHecquet** [comment]
@weierophinney, sorry for the delay (and to failing my commit 44f0408 message "git")
You have now some tests !

**Comment by weierophinney** [comment]
Merged to develop for release with 2.4.

**Pull request closed without merging**
