### PR TITLE
Request from string

### PR DESCRIPTION
**Pull request by mathiasverraes**
``` php
<?php
$request = \Zend\Http\Request::fromString(
    "GET /?foo=bar HTTP/1.1\r\n\r\n"
);

var_dump($request->getQuery()->get('foo'));
// Expected "bar", got null
```

### CODE REVIEW

**Comment by mathiasverraes** [comment]
I've no idea why travis fails :-(

**Comment by anthonysterling** [comment]
It looks like [Zend\Http\Request::setUri](https://github.com/zendframework/zf2/blob/master/library/Zend/Http/Request.php#L94) delegates the parsing of Query to [Zend/Uri/Uri](https://github.com/zendframework/zf2/blob/master/library/Zend/Uri/Uri.php#L332).

I suspect it's getting passed `/?foo=bar` and not `?foo=bar` so this [pattern](https://github.com/zendframework/zf2/blob/master/library/Zend/Uri/Uri.php#L332) never matches.

Maybe.

**Comment by mathiasverraes** [comment]
Did you find a place in the travis builds that fails?

**Comment by texdc** [comment]
Not sure, but it I'd guess that there's an issue with Travis, not the code or build.

**Comment by Ocramius** [comment]
I'll check the CS fixes locally: we handled this in `develop`, but not in `master`, so it's indeed a bit annoying to not be able to see the failures.

**Comment by Ocramius** [comment]
Merged, thanks @mathiasverraes!

`master`: zendframework/zf2@7e704a7ef336804171020844e310516d7a2ef38c
`develop`: zendframework/zf2@bef1fc181b6e16a8155f34fa3cac098d56df88af

**Comment by mathiasverraes** [comment]
YW, thanks for getting this in fast :-)

**Pull request merged**
