### PR TITLE
MongoDB to MongoDb

### PR DESCRIPTION
**Pull request by marc-mabe**
Our coding style defines names to be in CamelCase but this one was MIXEDCase.
The cache adapter wasn't released until now so this is no BC break but the session save handler and the log writer i thing. But normally PHP classes and methods are case-insensitive so this can only be an issue with some autoloaders on case-sensitive fs.

I think it's OK for the next minor release.

@Ocramius thoughts ?

### CODE REVIEW

**Comment by weierophinney** [comment]
@Ocramius and @marc-mabe : this is a BC break, plain and simple. While many (most?) people will be using the SM in order to setup the log, cache, and session adapters, the problem is that anybody who was manually instantiating the classes previously now has broken code, as the classes will no longer resolve — and, frankly, for no good or apparent reason. CS should have been considered _before_ releasing these as stable; once we go stable, we have to live with the names until the next major revision.

I'm thinking we should revert this, and we can re-apply for 3.0.

I'm flagging this to revert.

**Comment by weierophinney** [comment]
I've reverted this in the current develop branch.

@marc-mabe Please re-submit after we break the cache component into its own repo, and we can start considering v3 patches.

**Comment by Ocramius** [comment]
@weierophinney why did you revert? This stuff was not yet in a stable tag.

**Comment by weierophinney** [comment]
DAMMIT! I missed that aspect. Reverting the revert...

**Pull request merged**
