### PR TITLE
Happy new year 2015 : master

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
ping @Ocramius @weierophinney I've updated copyright year from 2014 to 2015 in master.

**Comment by Ocramius** [comment]
@samsonasik I'll merge this one and close #7088, otherwise we will just have a merge mess later on :-\

**Comment by Ocramius** [comment]
@samsonasik merged, thanks. I'll look for leftovers in `develop` now.

`master`: zendframework/zf2@8b644e8b0e8cd931bf25cf3babc3ffa047df26d5
`develop`: zendframework/zf2@1afa0410b64685d81b0e861c36bc3d4595a4ad7a

**Comment by Ocramius** [comment]
New files in `develop` handled at zendframework/zf2@d630a7f3b9874acea45871572cb3e78e7da51853

**Pull request closed without merging**
