### PR TITLE
Update PHP CS Fixer to v1.7

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by Maks3w** [comment]
This is supersede by #7477 and https://github.com/zendframework/zf2/commit/d2bda8f1a0b36222641fa79b6ca5c72c15cc1236

Thank you anyway

**Comment by keradus** [comment]
@Maks3w , I can't see any relation with #7477.
Also, on develop branch there is no caching enabled.

**Comment by Maks3w** [comment]
No there was not relation. Last commit in the branch do a global update.

About the caching thing if you want you can create a PR only with that. However I don't see benefits with the inminent component split

**Comment by keradus** [comment]
If sth can be done faster why not take advantages of it?
Even after component split ;)

**Comment by Maks3w** [comment]
I would like to hear how that cache works. With component split php-cs-fixer is only executed once and temporal files are not persisted across builds.

**Comment by Maks3w** [comment]
Also in the actual configuration all commands are executed in parallel at the same time so a lot of threads are prone to rebuild the cache due race conditions.

**Comment by keradus** [comment]
One can want to run the fixer locally before sending PR.
In brief when using cache file is not trying to fix again if file itself wasn't changed and using same PHP CS Fixer version. More info available at tool's page.

**Comment by Maks3w** [comment]
@keradus If you think is needed please open a PR with only that feature and describe the benefits and possible issues.

**Comment by keradus** [comment]
It is not needed, just cool to have.
If you see no point of it then cool, no need for new PR.

**Pull request closed without merging**
