### PR TITLE
Return all the messages loaded in the Translator

### PR DESCRIPTION
**Pull request by pensiero**
Added public method to the I18n\Translator that return all the messages loaded in the Translator: useful in case we want to manage all of them with some tools (refactoring, find&replace, po2json).

### CODE REVIEW

**Comment by Gamempire** [comment]
Forgot to mention that this code was originally posted by @juriansluiman on StackOverflow. Thanks @juriansluiman :+1:

**Comment by prolic** [comment]
Can you add tests, please?

**Comment by gianarb** [comment]
Can you submit this PR into the correct repository?! :) [zend-i18n](https://github.com/zendframework/zend-i18n) 

Thanks!

**Comment by Martin-P** [comment]
@gianarb Perhaps it is in idea to communicate to the community ZF2 is split in separate components?

**Comment by gianarb** [comment]
eheh :) I hope it.. But I don't know what is the idea about this stuff..

**Comment by weierophinney** [comment]
@Martin-P Will do, but need to get the code *out* of this one, first, because there will be confusion until we do. We're working on it.

**Comment by Gamempire** [comment]
Ok, I'll move this PR to https://github.com/zendframework/zend-i18n with some tests

**Comment by gianarb** [comment]
Thanks!!

Gianluca Arbezzano
Il 20/mag/2015 11:11, "Oscar Fanelli" <notifications@github.com> ha scritto:

**Comment by Gamempire** [comment]
Done! https://github.com/zendframework/zend-i18n/pull/2

**Pull request closed without merging**
