### PR TITLE
Feature: Added sslverifypeer to curl adapter

### PR DESCRIPTION
**Pull request by ins0**
the option can be set through the `curloptions` but in many projects this option is global shared through `sslverifypeer` as in every other adapter allready implement.

### CODE REVIEW

**Comment by Ocramius** [comment]
Should land only in `develop`, as it's a new feature.

**Comment by ins0** [comment]
my bad, create a new pr`?

**Comment by Ocramius** [comment]
No, should be fine, it's just a note for whoever is merging this.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by weierophinney** [comment]
Merged to develop for release in 2.4.

**Comment by ins0** [comment]
thanks @weierophinney

**Pull request closed without merging**
