### PR TITLE
fix project's CS

### PR DESCRIPTION
**Pull request by keradus**
why, why the CS on develop branch are broken :(

### CODE REVIEW

**Comment by keradus** [comment]
hurray, dead on `phpcov`

**Comment by gianarb** [comment]
I don't know the future of this repository.. But now all components are splitted in different repository.. 
I don't know if this fix is applicable

**Comment by keradus** [comment]
In Symfony we have components splitted into different repositories, but they are subtrees and read-only, all patches go to the root project.
Don't know how it is here.

**Comment by harikt** [comment]
@keradus it was the same a few days back. But now all components accepts PR and issues. So this repo may be staying for historical reasons probably from now on or may be removed ? But the PR can be send to individual component I guess.

**Comment by prolic** [comment]
:+1:

**Pull request closed without merging**
