### PR TITLE
Respecting line endings in AnnotationScanner

### PR DESCRIPTION
**Pull request by waltertamboer**
The annotation scanner only checked for line feeds ("\n"), carriage returns were not respected causing problems on files that were contained Mac or Windows line endings ("\r" or "\r\n").

### CODE REVIEW

**Comment by waltertamboer** [comment]
@Ocramius Done. Sorry for the delay. I updated the existing unit test so that it is tested with all type of line endings.

**Comment by Ocramius** [comment]
@waltertamboer thanks!

**Comment by Ocramius** [comment]
@waltertamboer merged, thanks.

`master`: zendframework/zf2@948f9175ef0a9f5d9fed7ab333580ab88376176e
`develop`: zendframework/zf2@fc4676add56af1740f22e7669d4d1a3d592a6ab3

**Comment by Ocramius** [comment]
@waltertamboer one remark, please **never ever EVER** merge `master` or `develop` into a `feature/` or `hotfix/` branch, as it messes with `git bisect` if a problem arises in future.

Instead, use `git rebase`, and also be very careful to never `git pull` without also using the `--ff-only` flag, as `pull` does automatically merge otherwise.

I simply cherry-picked the commits out of this PR, so it doesn't result as merged, but just as closed.

Thanks for sorting this out, very simple and clean fix :-)

**Comment by waltertamboer** [comment]
Lesson learned. Thanks

**Pull request closed without merging**
