### PR TITLE
Oracle quoting fix for values with single quotes

### PR DESCRIPTION
**Pull request by marcelto**
Single quotes need to be handled differently

$str = 'foo \'bar';
echo 'select '.$oracleAdapterPlatform->quoteTrustedValue($str).'from dual';//sql string won't run in Oracle(11.2.0.4.0 in this case)

outputs: select 'foo \'bar' from dual

needs to output: select 'foo ''bar' from dual

### CODE REVIEW

**Comment by macnibblet** [comment]
Can you add a test case ?

**Comment by MarcelTO** [comment]
Sorry I'm still a little new to pull requests.  Do you mean an assertion in the Oracle unit test?

**Comment by macnibblet** [comment]
You need to add a test case in https://github.com/zendframework/zf2/blob/master/tests/ZendTest/Db/Adapter/Platform/OracleTest.php so we don't have any regressions.

**Comment by MarcelTO** [comment]
Ah yes, I see.

**Comment by MarcelTO** [comment]
Priority issue at work, will fix delete assertions in unit test asap

**Comment by macnibblet** [comment]
:+1:

**Comment by weierophinney** [comment]
Merged to develop for release with 2.4.

**Pull request closed without merging**
