### PR TITLE
CS: Ordering use statements

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by keradus** [comment]
Should I do sth else in this PR @Ocramius ?

**Comment by Ocramius** [comment]
@keradus I'd keep this sort of CS fix as last due to the huge amount of possible conflicts with PRs still open for [2.4.0](https://github.com/zendframework/zf2/milestones/2.4.0)

**Comment by keradus** [comment]
I see. Thanks for info!

**Comment by weierophinney** [comment]
Closing. The size of this is huge, and I think it will be easier to do this successfully when we do the component split following the 2.4 release.

**Comment by keradus** [comment]
:(

**Pull request closed without merging**
