### PR TITLE
Exception message in Zend\Stdlib\AbstractOptions should use the actual used setter

### PR DESCRIPTION
**Pull request by Martin-P**
The current exception message uses some fabricated setter which is not even used in the actual test in [`Zend\Stdlib\AbstractOptions` line 103](https://github.com/zendframework/zf2/blob/67f098af070b29d5042e89e936604df3193d2212/library/Zend/Stdlib/AbstractOptions.php#L103).

This PR changes the exception message and makes it use the actual used setter and thus creates a more accurate message. See: https://github.com/zendframework/zf2/issues/7155#issuecomment-71451833

### CODE REVIEW

**Comment by Martin-P** [comment]
Was thinking about changing the value of `$setter` itself, but it seems the usage of an actual different `$setter` value was a minor performance tweak added in https://github.com/zendframework/zf2/commit/f07104142881de54c1131ebb5fabca781f532563.

**Comment by Ocramius** [comment]
I know I'm pedantic here, but can haz test?

**Comment by Martin-P** [comment]
I added a test for the exception message, but I may hope nobody uses the exception message itself as a way to test which exception is thrown.

**Comment by Ocramius** [comment]
>  may hope nobody uses the exception message itself as a way to test which exception is thrown

Yeah, it's not about that, it's mainly about the usual "cast to string" and such errors ;-)

**Comment by Ocramius** [comment]
@Martin-P merged, thanks!

Had to manually apply changes to the `develop` rebase due to conflicts, no big deal tho.

`master`: zendframework/zf2@49f3986a5e450f758dc5d337f8e08904c8c3613b
`develop`: zendframework/zf2@5d6570fda809c68c829e49ca56b599f6972e81bf

**Pull request closed without merging**
