### PR TITLE
Add a rule for the Luxembourgish telco Join

### PR DESCRIPTION
**Pull request by rwellens**
There is a new telecom operator in Luxembourg with numbers starting 671

### CODE REVIEW

**Comment by Ocramius** [comment]
Requires:

 - rebase
 - additional test case with example numbers (to prevent regressions)

**Comment by samsonasik** [comment]
@rwellens if you want to target to develop, you should start with your develop branch, not master. and should be better with new branch checked out from develop.

**Comment by weierophinney** [comment]
@samsonasik It's rarely a problem due to our merge process; anything that merges cleanly to master will generally merge cleanly to develop. We only need users to target develop if there are changes in that branch that will conflict.

**Comment by weierophinney** [comment]
@rwellens We still need some test cases, as requested by @Ocramius .

**Comment by weierophinney** [comment]
24-hour warning; I need tests by tomrrow, 19 March 2015, if you want this included in 2.4; otherwise, I'll remove the milestone, and we can review at a later date.

**Comment by GeeH** [comment]
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-i18n/issues/51

**Pull request closed without merging**
