### PR TITLE
added zendframework/zendxml into suggest at Zend\Json's composer.json

### PR DESCRIPTION
**Pull request by samsonasik**
used by <code>Zend\Json\Json::fromXml()</code>

### CODE REVIEW

**Comment by rakesh-beedasy** [comment]
Why is Zend\Xml2Json\Xml2Json::fromXml marked as deprecated in zf3 ?

**Comment by weierophinney** [comment]
> Why is Zend\Xml2Json\Xml2Json::fromXml marked as deprecated in zf3 ?

It's not; the method for doing so in `Zend\Json\Json` has been extracted into its own package, [zendframework/zend-xml2json](https://zendframework.github.io/zend-xml2json).

**Comment by rakesh-beedasy** [comment]
https://github.com/zendframework/zend-xml2json/blob/master/src/Xml2Json.php#L45

**Comment by samsonasik** [comment]
@rakesh-beedasy I've created PR for @deprecated doc removal for that: https://github.com/zendframework/zend-xml2json/pull/1

**Comment by rakesh-beedasy** [comment]
Thanks :+1:

**Pull request merged**
