### PR TITLE
Add flexibility to FlashMessenger by determining hops as parameter.

### PR DESCRIPTION
**Pull request by ASvi**
Additional flexibility for FlashMessenger. It's better to determine hops as parameter.

### CODE REVIEW

**Comment by asvgit** [comment]
Also hops flexibility can be implemented on error, warning, success and info messages.

**Comment by weierophinney** [comment]
Please add a unit test for this functionality.

**Comment by asvgit** [comment]
Test added

**Comment by weierophinney** [comment]
We have a problem at this point. The feature you're suggesting conflicts with a feature already in the develop branch, which adds `$namespace` as an optional second parameter.

I'm going to go ahead and merge this, but will put `$hops` as the **third** parameter in this case.

**Comment by weierophinney** [comment]
Merged to develop for release with 2.4.

**Comment by weierophinney** [comment]
Marking as a BC break, as it changes signature.

**Pull request closed without merging**
