### PR TITLE
Typo in #6598 pull request.

### PR DESCRIPTION
**Pull request by filipp-kucheriavenko**
Fixing of IntlException instance name

### CODE REVIEW

**Comment by Ocramius** [comment]
Urgh, this is obviously because I couldn't get to write a test case for that exception -.- Thanks for spotting it!

**Comment by filipp-qoma** [comment]
You welcome =). By the way, this exception exists in PHP >=5.5.0. I don't know how PHP < 5.5.0 will behave in this situation. I will try to write test for this when I have time.

**Comment by Ocramius** [comment]
@filipp-qoma <5.5.0 uses a manual throwing mechanism

**Comment by Ocramius** [comment]
@filipp-qoma merged, thanks!

`master`: zendframework/zf2@f6a01fc2879be05e608196dd73cb925a47382664
`develop`: zendframework/zf2@56bb6fea69556add75dfabed75565e99559b9f4f

**Pull request closed without merging**
