### PR TITLE
[WIP] Make ZF2 a meta-package

### PR DESCRIPTION
**Pull request by gianarb**
- remove library and tests folder
- Update composer.json
- Remove travis php_cs and converalls configurations

ping @ezimuel :)

### CODE REVIEW

**Comment by weierophinney** [comment]
@gianarb and @ezimuel — I pulled the branch locally, and made some additional changes, which you can see here:

- https://github.com/weierophinney/zf2/tree/feature/7542

The changes include:

- Removal of the `demos/` directory
- Removal of `vendor/.gitignore`, and addition of `vendor/` to `.gitignore`
- Auditing of the scripts under `bin/` (most were removed; those that remain required changes to how autoloading works)
- Updated the `composer.json` to **require** all existing components, at a version of `~2.4`.
- Consolidated `CONTRIBUTING.md` and `README-GIT.md`, as we did in the component repos, and added links to all component repos.
- Minor updates to the `INSTALL.md`, `README.md`, and `.gitattributes` files.

Unfortunately, I'm having issues with the github API rate limit (as it turns out, the 5000 limit is for *authenticated* users, and once you hit that, you have no recourse but to wait), so I was unable to validate that (a) `composer install --prefer-dist` works, and/or (b) update the ZF2 composer repository (which was still pointing at the old repos). Hopefully I can resolve those two issues soon to verify.

@gianarb If you want to check out my branch and attempt to install, feel free.

**Comment by weierophinney** [comment]
> I was unable to validate that (a) composer install --prefer-dist works

It doesn't right now, because most repos still use `self.version` to specify dependencies, which means that we get 2.4.0 versions for almost everything. I'll update all repos to remove that tomorrow, and issue the 2.5.0 release on each, which should fix things.

**Comment by gianarb** [comment]
@weierophinney I'm trying to run `composer install --prefer-dist`

```
✔ ~/git/zf2 [feature/7542|✔]
01:04 $ composer install --prefer-dist
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing zendframework/zend-stdlib (2.4.0)
    Loading from cache

  - Installing zendframework/zend-escaper (2.4.0)
    Loading from cache

  - Installing zendframework/zend-tag (2.4.0)
    Loading from cache

  - Installing zendframework/zendxml (dev-master 3dcfc87)
    Loading from cache

  - Installing zendframework/zend-eventmanager (2.4.0)
    Loading from cache

  - Installing zendframework/zend-code (2.4.0)
    Loading from cache

  - Installing zendframework/zend-server (2.4.0)
    Loading from cache

  - Installing zendframework/zend-math (2.4.0)
    Loading from cache

  - Installing zendframework/zend-validator (2.4.0)
    Loading from cache

  - Installing zendframework/zend-uri (2.4.0)
    Loading from cache

  - Installing zendframework/zend-loader (2.4.0)
    Loading from cache

  - Installing zendframework/zend-http (2.4.0)
    Loading from cache

  - Installing zendframework/zend-xmlrpc (2.4.0)
    Loading from cache

  - Installing zendframework/zend-servicemanager (2.4.0)
    Downloading: 100%

  - Installing zendframework/zend-text (2.4.0)
    Downloading: 100%

  - Installing zendframework/zend-view (2.4.0)
    Downloading: 100%

  - Installing zendframework/zend-filter (2.4.0)
    Downloading: 100%

  - Installing zendframework/zend-inputfilter (2.4.0)
    Downloading: 100%

  - Installing zendframework/zend-form (2.4.0)
    Downloading: 100%

  - Installing zendframework/zend-mvc (2.4.0)
    Downloading: 100%

  - Installing zendframework/zend-dom (2.4.0)
    Downloading: 100%

  - Installing zendframework/zend-console (2.4.0)
    Downloading: 100%
.....
```

**Comment by Maks3w** [comment]
So what will be the feature of zend-resources?

**Comment by weierophinney** [comment]
@gianarb I found the issue; I'd not updated packagist's zend-tag definition, which meant it was pointing at the old repository, and thus only had through the 2.4.0 tag. Considering that it had dependencies on escaper, stdlib, and servicemanager, those were then each locked to 2.4.0, which meant any component depending on any of those was locked to 2.4.0, and so on down the chain.

Should be correct now!

**Comment by gianarb** [comment]
Ok @weierophinney ! :) Now do you add zend-i18n-resources in Zend\I18n composer.json? :+1:

**Comment by weierophinney** [comment]
> So what will be the feature of zend-resources?

- https://github.com/zendframework/zend-i18n-resources

We never actually shipped a zend-resources package, and thus the "replace" entry for it was moot. Since the package is strictly i18n translation resources, I namespaced it as such. The package is now on packagist, and will be on packages.zendframework.com as soon as I can get that switched over to the new component repos (I've been fighting with it off and on for a week; I keep hitting either API limits or silent failures from satis).

**Comment by weierophinney** [comment]
> Ok @weierophinney ! :) Now do you add zend-i18n-resources in Zend\I18n composer.json?

Yes; see the last commit. :)

**Comment by weierophinney** [comment]
> @gianarb I found the issue; I'd not updated packagist's zend-tag definition,

Now that it's updated, I'm getting 2.4.2 versions across the board! :tada:

**Comment by gianarb** [comment]
go go go!!! :D

**Comment by weierophinney** [comment]
As a final test, I cloned [zendframework/ZendSkeletonApplication](https://github.com/zendframework/ZendSkeletonApplication), and updated the `composer.json` to read as follows:

```json
{
    "name": "zendframework/skeleton-application",
    "description": "Skeleton Application for ZF2",
    "license": "BSD-3-Clause",
    "keywords": [
        "framework",
        "zf2"
    ],
    "homepage": "http://framework.zend.com/",
    "repositories": [
      {"type": "vcs", "url": "https://github.com/weierophinney/zf2.git"}
    ],
    "require": {
        "php": ">=5.3.3",
        "zendframework/zendframework": "dev-feature/7542@dev"
    }
}
```

and then ran `composer install`. Installation worked flawlessly (it installed each component at 2.4.2), and, better, running `php -S 0:8888 -t public/ public/index.php` and browsing to `localhost:8888` showed the skeleton application successfully!

**Comment by gianarb** [comment]
Perfect news! And now we are ready to delete ZF ehehe..

Gianluca Arbezzano
Il 28/mag/2015 18:08, "weierophinney" <notifications@github.com> ha scritto:

**Comment by weierophinney** [comment]
Merged to develop!

**Pull request closed without merging**
