### PR TITLE
[wip] Added $data param to deleteList

### PR DESCRIPTION
**Pull request by TomHAnderson**
deleteList was not passed any data.  This corrects the abstract function declaration for deleteList and adds data parsing and passing to the onDispatch event.

### CODE REVIEW

**Comment by samsonasik** [comment]
need test.

**Comment by weierophinney** [comment]
@TomHAnderson Need a test case so we can get this into 2.4.

**Comment by TomHAnderson** [comment]
Moving this to a new non-wip PR

**Comment by TomHAnderson** [comment]
Moved to https://github.com/zendframework/zf2/pull/7255

**Pull request closed without merging**
