### PR TITLE
Fix 5.3 test failure

### LINKED ISSUE #7704: phpunit fails on php5.3, since release-2.4.10
tests/ZendTest/Mail/Header/HeaderValueTest.php fails on php5.3, because of short array syntax.
I have not able to send PR because release-2.4.10 does not belong to any branches.

### PR DESCRIPTION
**Pull request by nosenaoki**
This PR fixes #7704

### CODE REVIEW

**Comment by Xerkus** [comment]
needs rebase, a lot of unrelated commits

**Comment by nosenaoki** [comment]
@Xerkus Even if I rebase my commit onto tag 2.4.10, I can't re-send PR because tag 2.4.10 does not belong to any branch. What should I do?

**Comment by Xerkus** [comment]
@nosenaoki rebase onto target branch, release-2.4

**Comment by nosenaoki** [comment]
@Xerkus  I can't rebase only my commit onto the branch release-2.4, because my fix is for e3d5a4efeaa5f7640cd96aafad5cd08ad25fbff1 which precedes the tag release-2.4.10.

**Comment by Xerkus** [comment]
@weierophinney your attention is needed here, i suppose

**Comment by weierophinney** [comment]
Relevant commit is 	3850aeb ... which, contrary to the report, is not about broken tests, but PHP 5.4isms that are in *source code*.

I'll try and schedule a new release this week. Unfortunately, these LTS releases are non-trivial to accomplish, so I cannot give a concrete date.

**Comment by samsonasik** [comment]
ping @weierophinney

**Comment by nosenaoki** [comment]
@weierophinney  I'm waiting for this PR to be merged.

**Comment by Xerkus** [comment]
Sorry, this PR got lost in backlog as this repo is mostly inactive after the component split.

LTS for the 2.4 series ended over a year ago, there will be no new releases. I am going to close this PR now.

**Pull request closed without merging**
