### PR TITLE
Move test components to require-dev

### LINKED ISSUE #7574: zend-test module installs phpunit in production environment
maybe make zend-test optional? Is it really required? or at least add it to "require-dev" not "require"

### PR DESCRIPTION
**Pull request by Maks3w**
Close https://github.com/zendframework/zf2/issues/7574

### CODE REVIEW

**Comment by gianarb** [comment]
:+1:

**Comment by malukenho** [comment]
:+1:

**Comment by stefanotorresi** [comment]
is there any reason why this is marked for 3.0 instead of a minor? isn't this a bugfix? :(

**Comment by Moln** [comment]
Is there a plan to fix it?

**Review by darielopper — APPROVED** [review]

**Comment by weierophinney** [comment]
Installing the framework via the metapackage is no longer recommended. **IF** we update to version 4, we can address at that time; in the meantime, it would be a backwards compatibility break for anybody who relied on it being installed previously.

**Comment by Xerkus** [comment]
This package will not receive any new releases after upcoming Laminas migration.

**Pull request closed without merging**
